package com.hresources.hr.policy_assistant.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

/**
 * Response payload returned after RAG answer generation completes.
 *
 * @param question original question submitted by the caller
 * @param answer answer generated by the language model from retrieved context
 * @param model language model used to generate the answer
 * @param retrievalStrategy retrieval approach used to produce the answer
 * @param citations citations referencing the chunks used in the answer
 * @param retrievedChunks ranked chunks retrieved from the vector store
 */
public record PolicyAnswerResponse(
        @Schema(description = "Original question submitted by the caller.")
        String question,
        @Schema(description = "Answer generated from retrieved policy context.")
        String answer,
        @Schema(description = "Name of the chat model used to generate the answer.", example = "gpt-4.1-mini")
        String model,
        @Schema(description = "Name of the retrieval strategy used to answer the question.", example = "pgvector-openai-rag")
        String retrievalStrategy,
        @Schema(description = "Citations referencing the retrieved policy chunks used to answer the question.")
        List<PolicyCitationResponse> citations,
        @Schema(description = "Top ranked retrieved chunks considered while answering the question.")
        List<PolicyMatchResponse> retrievedChunks
) {
}
